server {
    listen 80 default_server;

    client_max_body_size 12M;

    root /var/www/html;
    index index.php index.html;

    location /testconf/ {
        fastcgi_pass hotcrp:9000;

        fastcgi_split_path_info ^(/testconf)(/.*)$;

        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        include fastcgi_params;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass hotcrp:9000;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /stylesheets { try_files $uri =404; }
    location /scripts { try_files $uri =404; }
    location /images { try_files $uri =404; }
}